/**
 * Japanese for copy that upstream added with Orchestration V2 (2026-10) and
 * that uiText.ja.ts did not have yet. Collected from the running app; see
 * amu/domTranslation.ts. Keys are the upstream English, before Amu's
 * renaming, so "T3 Code" stays in a key when the source says it.
 */
export const japaneseUiTextV2: Readonly<Record<string, string>> = {
  // Times (numbers only; see domTranslation.ts)
  "{0}m ago": "{0}分前",
  "{0}h ago": "{0}時間前",
  "{0}d ago": "{0}日前",
  "{0}w ago": "{0}週間前",
  "{0}mo ago": "{0}か月前",
  "{0}m": "{0}分",
  "{0}h": "{0}時間",
  "{0}d": "{0}日",
  "{0}w": "{0}週間",
  "{0} clients": "{0} 台のクライアント",
  "Settled ({0})": "完了済み（{0}）",

  // Codex image generation rows (Amu)
  "Generated image": "生成した画像",
  "Generating image": "画像を生成しています",
  "Image generation failed": "画像を生成できませんでした",
  "Image generation stopped": "画像の生成を中止しました",

  // Chat and sidebar
  "Add a project, or start without one.": "プロジェクトを追加するか、プロジェクトなしで始めます。",
  "Start without a project": "プロジェクトなしで始める",
  "No project": "プロジェクトなし",
  "T3 Code collects anonymous usage data to help us improve it. To read more about how your data is used and how to opt out, see our":
    "Amu は改善のため、匿名の利用データを集めています。データの使い方と止め方の説明は",
  "privacy policy": "プライバシーポリシー",
  "or start without a project": "またはプロジェクトなしで始める",
  "New thread without a project": "プロジェクトなしの新しいスレッド",
  "New thread in {0}": "{0} に新しいスレッド",
  "What should we build in {0}?": "{0} で何を作りましょうか？",
  "Add project script": "プロジェクトのスクリプトを追加",
  "Next turn": "次のターン",
  "Previous turn": "前のターン",
  "Submit message": "メッセージを送信",
  "Toggle thread details panel": "スレッドの詳細パネルを切り替え",
  "Maximize panel": "パネルを最大化",
  "PR #{0}, status {1}": "PR #{0}・状態：{1}",
  "Version Control": "バージョン管理",
  "Search commands, projects, and threads...": "コマンド・プロジェクト・スレッドを検索...",
  "{0} — Unavailable. {1}": "{0}：使えません。{1}",
  "Sign in with Cursor or add CURSOR_API_KEY in provider settings.":
    "Cursor にサインインするか、プロバイダーの設定で CURSOR_API_KEY を追加してください。",
  "· Sign in with Cursor or add CURSOR_API_KEY in provider settings.":
    "・Cursor にサインインするか、プロバイダーの設定で CURSOR_API_KEY を追加してください。",
  "Last user message": "最後のユーザーメッセージ",
  "· Created": "・作成",
  Composer: "入力欄",
  Other: "その他",
  Archived: "アーカイブ済み",

  "Context handoff": "引き継ぎ",
  "Update Available: {0}": "更新があります：{0}",
  "Check for updates": "更新を確認",
  "Provider error": "プロバイダーのエラー",

  // Settings
  "Scheduled Tasks": "予定タスク",
  "Scheduled tasks": "予定タスク",
  "No scheduled tasks": "予定タスクはありません",
  "No tasks match this environment and project selection.":
    "この環境とプロジェクトの選択に合うタスクはありません。",
  "New task": "新しいタスク",
  Weekly: "毎週",
  "Auto-resume limited threads": "上限で止まったスレッドを自動で再開",
  "Automatically resume interrupted threads after an update, crash, or machine restart on the selected environments.":
    "選んだ環境で、更新・クラッシュ・再起動で中断したスレッドを自動で再開します。",
  "Snooze limited threads": "上限で止まったスレッドをスヌーズ",
  "Snooze usage-limit stops until the reported reset time. Combine with auto-resume to continue when they wake.":
    "利用上限で止まったスレッドを、上限が戻る時刻までスヌーズします。自動再開と組み合わせると、戻ったときに続きから始めます。",
  "Resume usage-limit stops at the reported reset time. Each thread can cancel its scheduled continuation.":
    "利用上限で止まったスレッドを、上限が戻る時刻に再開します。予定した再開はスレッドごとに取り消せます。",
  "Branch prefix": "ブランチの接頭辞",
  "Static prefix": "固定の接頭辞",
  "No prefix": "接頭辞なし",
  "Worktree branch naming": "ワークツリーのブランチ名の付け方",
  "Choose how new worktree branches are named from your first message.":
    "最初のメッセージから、新しいワークツリーのブランチ名をどう付けるかを選びます。",
  "Worktree location": "ワークツリーの場所",
  "Folder where new worktrees are created, on any drive, such as D:\\worktrees or ~/worktrees. Existing worktrees stay where they are. Leave empty to use the T3 home folder.":
    "新しいワークツリーを作るフォルダーです（例：D:\\worktrees、~/worktrees）。どのドライブでも使えます。今あるワークツリーは動きません。空にすると Amu のホームフォルダーを使います。",
  "Keep branch and worktree controls below the composer after a thread starts.":
    "スレッドを始めたあとも、入力欄の下にブランチとワークツリーの操作を出したままにします。",
  "Keep composer context visible in active threads":
    "進行中のスレッドで入力欄の文脈を出したままにする",
  "Composer context": "入力欄の文脈",
  "Working section (beta)": "作業中のセクション（ベータ）",
  "Project order": "プロジェクトの並び順",
  "Terminal input": "ターミナルの入力",
  "Terminal scrollback": "ターミナルのスクロールバック",
  "Toggle account email visibility": "アカウントのメールアドレスの表示を切り替え",
  "Environment scope: {0}": "環境の範囲：{0}",
  "All environments": "すべての環境",
  "Project scope: {0}": "プロジェクトの範囲：{0}",
  "All projects": "すべてのプロジェクト",
  "Snapshot sound: {0}": "スナップショットの音：{0}",
  "Sort pull requests: {0}": "プルリクエストの並べ替え：{0}",
  "Merge readiness": "マージの準備状況",
  "Account-specific Codex home. Keeps auth.json separate while sharing state from CODEX_HOME.":
    "アカウントごとの Codex のホームです。CODEX_HOME の状態は共有したまま、auth.json だけを分けて持ちます。",
  "Add a Bitbucket token in Settings → Source Control.":
    "設定 → ソース管理で、Bitbucket のトークンを追加してください。",
  "Additional CLI arguments passed to codex app-server on session start.":
    "セッションの開始時に codex app-server へ渡す追加の CLI 引数です。",
  "Allow new agent sessions in this environment to start and control local and remote devices, with required tools set up automatically.":
    "この環境の新しいエージェントのセッションが、ローカルとリモートのデバイスを起動・操作できるようにします。必要なツールは自動で用意します。",
  "Authenticated · {0}": "認証済み・{0}",
  "Available.": "利用できます。",
  "Capture a window and attach it to your current draft.":
    "ウィンドウを撮影して、今の下書きに添付します。",
  "Custom Codex home and config directory.": "Codex のホームと設定フォルダーを指定します。",
  "Fast mode · Reasoning": "高速モード・推論",
  "How we handle your data, including the anonymous usage data T3 Code collects.":
    "データの扱い（アプリが集める匿名の利用データを含む）",
  "Launch arguments": "起動時の引数",
  "Not authenticated": "未認証",
  "Not available on this server:": "このサーバーでは使えません：",
  "Path to the Codex binary used by this instance.":
    "このインスタンスが使う Codex の実行ファイルのパスです。",
  "Privacy policy": "プライバシーポリシー",
  "Shortcut saved.": "ショートカットを保存しました。",
  "Your default browser": "既定のブラウザー",
  "Reopen Closed Tab": "閉じたタブを開き直す",
  "Past 24h ({0})": "過去 24 時間（{0}）",
  "{0} days ({1})": "{0} 日（{1}）",
  "Cost ({0})": "費用（{0}）",
  "Limits ({0})": "上限（{0}）",
  "Tokens ({0})": "トークン（{0}）",

  // Keyboard shortcut commands
  "Chat: New": "チャット：新規",
  "Chat: New Local": "チャット：ローカルで新規",
  "Chat: New Without Project": "チャット：プロジェクトなしで新規",
  "Command Palette: Toggle": "コマンドパレット：切り替え",
  "Composer: Branch": "入力欄：ブランチ",
  "Composer: Effort": "入力欄：思考の強さ",
  "Composer: Host": "入力欄：ホスト",
  "Composer: Mode": "入力欄：モード",
  "Composer: Opposite Queue or Steer Action": "入力欄：キューと割り込みを入れ替えて送る",
  "Composer: Previous Worktree": "入力欄：前のワークツリー",
  "Composer: Send and Start New Thread": "入力欄：送信して新しいスレッドを始める",
  "Composer: Start in Background": "入力欄：裏で始める",
  "Composer: Stash": "入力欄：一時退避",
  "Composer: Workspace": "入力欄：ワークスペース",
  "Diff: Toggle": "差分：切り替え",
  "Editor: Open Favorite": "エディター：お気に入りを開く",
  "File Picker: Toggle": "ファイル選択：切り替え",
  "Model Picker: Jump: {0}": "モデル選択：{0} 番目へ",
  "Model Picker: Next Provider": "モデル選択：次のプロバイダー",
  "Model Picker: Previous Provider": "モデル選択：前のプロバイダー",
  "Model Picker: Toggle": "モデル選択：切り替え",
  "Navigation: Back": "移動：戻る",
  "Navigation: Forward": "移動：進む",
  "Preview: Focus Url": "プレビュー：URL 欄へ",
  "Preview: Refresh": "プレビュー：再読み込み",
  "Preview: Reset Zoom": "プレビュー：拡大率を戻す",
  "Preview: Toggle": "プレビュー：切り替え",
  "Preview: Zoom In": "プレビュー：拡大",
  "Preview: Zoom Out": "プレビュー：縮小",
  "Project Search: Toggle": "プロジェクト検索：切り替え",
  "Pull Request: Copy Link or Thread ID": "プルリクエスト：リンクかスレッド ID をコピー",
  "Pull Request: Copy Number": "プルリクエスト：番号をコピー",
  "Queue: Edit Last Queued Message": "キュー：最後に入れたメッセージを編集",
  "Queue: Send First Queued Message as Steer": "キュー：最初のメッセージを割り込みで送る",
  "Right Panel: Close": "右パネル：閉じる",
  "Right Panel: New": "右パネル：新規",
  "Right Panel: Toggle": "右パネル：切り替え",
  "Sidebar: Toggle": "サイドバー：切り替え",
  "Split View: Close Pane": "画面の分割：ペインを閉じる",
  "Split View: Focus Next": "画面の分割：次のペインへ",
  "Split View: Focus Previous": "画面の分割：前のペインへ",
  "Split View: Split Down": "画面の分割：下に分割",
  "Split View: Split Right": "画面の分割：右に分割",
  "Terminal: Close": "ターミナル：閉じる",
  "Terminal: New": "ターミナル：新規",
  "Terminal: Split": "ターミナル：分割",
  "Terminal: Split Vertical": "ターミナル：縦に分割",
  "Terminal: Toggle": "ターミナル：切り替え",
  "Theme Editor: Toggle": "テーマエディター：切り替え",
  "Theme: Select": "テーマ：選ぶ",
  "Thread: Jump: {0}": "スレッド：{0} 番目へ",
  "Thread: Next": "スレッド：次へ",
  "Thread: Pin": "スレッド：ピン留め",
  "Thread: Previous": "スレッド：前へ",
  "Thread: Settle": "スレッド：完了にする",
  "Thread: Undo": "スレッド：元に戻す",
  "Usage: Cost": "使用量：費用",
  "Usage: Limits": "使用量：上限",
  "Usage: Open": "使用量：開く",
  "Usage: Period: Past 24h": "使用量：期間：過去 24 時間",
  "Usage: Tokens": "使用量：トークン",
};
