export const japaneseUiText: Readonly<Record<string, string>> = {
  Settings: "設定",
  General: "一般",
  Appearance: "外観",
  Keybindings: "キーボードショートカット",
  Providers: "プロバイダー",
  Integrations: "連携",
  "Source Control": "ソース管理",
  Storage: "保存領域",
  Connections: "接続",
  Archive: "アーカイブ",
  Project: "プロジェクト",
  Projects: "プロジェクト",
  Threads: "スレッド",
  Agents: "エージェント",
  Connect: "接続",
  Back: "戻る",
  Usage: "使用量",
  "Pull Requests": "プルリクエスト",
  Continue: "続ける",
  Cancel: "キャンセル",
  Close: "閉じる",
  Save: "保存",
  Delete: "削除",
  Remove: "削除",
  Rename: "名前を変更",
  Retry: "再試行",
  "Try again": "もう一度試す",
  Done: "完了",
  Skip: "スキップ",
  "Skip for now": "今はスキップ",
  "Select all": "すべて選択",
  "Deselect all": "選択を解除",
  Refresh: "更新",
  Install: "インストール",
  "Sign in": "ログイン",
  "Sign out": "ログアウト",
  Ready: "準備完了",
  "Checking...": "確認中…",
  Disabled: "無効",
  Enabled: "有効",
  Connected: "接続済み",
  "Connecting…": "接続中…",
  Connecting: "接続中",
  Available: "利用可能",
  Unavailable: "利用不可",
  "Not found": "見つかりません",
  "Not authenticated": "未ログイン",
  Authenticated: "認証済み",
  "Needs attention": "確認が必要",
  Computer: "コンピューター",
  "Local device": "このMac",
  "Primary device": "メインの端末",
  "Remote device": "リモート端末",
  Devices: "端末",
  "What should we work on?": "何を始めましょうか？",
  "Add a project to start your first thread.":
    "プロジェクトを追加して、最初のスレッドを始めましょう。",
  "Add project": "プロジェクトを追加",
  "New thread": "新しいスレッド",
  "New thread in...": "プロジェクトで新しいスレッド…",
  "Search projects": "プロジェクトを検索",
  "Search projects...": "プロジェクトを検索…",
  "Search settings": "設定を検索",
  "Search settings...": "設定を検索…",
  "Command palette": "コマンドパレット",
  "Go to threads": "スレッドへ戻る",
  "Thread title": "スレッド名",
  Pinned: "ピン留め",
  "Unpin thread": "ピン留めを解除",
  "Pin thread": "スレッドをピン留め",
  "Discard draft": "下書きを破棄",
  "Unsent draft": "未送信の下書き",
  "Snooze thread": "スレッドを一時休止",
  "Wake thread now": "スレッドを再開",
  "Settle thread": "スレッドを完了にする",
  "Un-settle thread": "スレッドを再開",
  "Set up T3 Code": "T3 Codeの初期設定",
  "Connect your computers": "コンピューターを選ぶ",
  "Choose one or more computers. We’ll set up agents and projects on each.":
    "利用するコンピューターを選びます。エージェントとプロジェクトを順に設定します。",
  "Computers to set up": "設定するコンピューター",
  "Add a computer": "コンピューターを追加",
  "Connect your agents": "エージェントを設定",
  "Choose an agent to start coding. You can add more later.":
    "使うエージェントを選びます。後から追加できます。",
  "Ready to code.": "コーディングを始められます。",
  "Choose your projects": "プロジェクトを選ぶ",
  "Your projects": "プロジェクト一覧",
  "Import projects and conversations from your selected computers.":
    "選択したコンピューターから、プロジェクトや会話を取り込めます。",
  "Other folders": "その他のフォルダー",
  "Importing…": "取り込み中…",
  "Pairing link": "ペアリングリンク",
  "Need a pairing link?": "ペアリングリンクの取得方法",
  "Pairing...": "ペアリング中…",
  Pair: "ペアリング",
  "Pairing failed.": "ペアリングに失敗しました。",
  "Run this on the computer with your code.": "コードを保存しているコンピューターで実行します。",
  "Copy command": "コマンドをコピー",
  "Review the command, then press Enter to run it.":
    "コマンドを確認し、Enterキーで実行してください。",
  "Could not open the setup terminal.": "設定用ターミナルを開けませんでした。",
  "Preparing command...": "コマンドを準備中…",
  "Could not finish setup": "初期設定を完了できませんでした",
  "Your settings could not be saved. Try again.":
    "設定を保存できませんでした。もう一度お試しください。",
  "Some history was not imported": "一部の履歴を取り込めませんでした",
  "Could not import thread history.": "スレッド履歴を取り込めませんでした。",
  "Scan limit reached. Some projects or conversations may be missing.":
    "検索件数の上限に達しました。一部のプロジェクトや会話が表示されていない可能性があります。",
  "Couldn’t start a new thread": "新しいスレッドを開始できませんでした",
  "The project is still available. Try opening the draft again.":
    "プロジェクトは利用できます。下書きをもう一度開いてください。",
  "Open Connections": "接続設定を開く",
  "Connect to a computer running T3 Code": "T3 Codeを実行しているコンピューターに接続",
  "Checking provider status": "プロバイダーを確認中",
  "Waiting for the server to report installation and authentication details.":
    "インストール状況と認証情報の確認を待っています。",
  "CLI not detected on PATH.": "PATH上にCLIが見つかりません。",
  "This provider is installed but disabled for new sessions in T3 Code.":
    "インストール済みですが、T3 Codeでの新しいセッションには無効です。",
  "The provider is installed, but the server could not fully verify it.":
    "インストール済みですが、動作を完全に確認できませんでした。",
  "The provider failed its startup checks.": "起動時の確認に失敗しました。",
  "Refresh provider status": "プロバイダーの状態を更新",
  "Update available": "更新があります",
  "Update for full support.": "完全なサポートには更新が必要です。",
  "Checked unavailable": "確認日時を取得できません",
  "Connected with your Codex CLI.": "既存のCodex CLIで接続済みです。",
  "Checking your Codex CLI...": "既存のCodex CLIを確認中…",
  "Code with your ChatGPT subscription.": "ChatGPTのサブスクで利用します。",
  "Use your ChatGPT subscription.": "ChatGPTのサブスクを利用します。",
  "Signed in with ChatGPT.": "ChatGPTでログイン済みです。",
  "Use existing Codex CLI": "既存のCodex CLIを使用",
  "Use installed Codex CLI": "インストール済みのCodex CLIを使用",
  "ChatGPT account": "ChatGPTアカウント",
  "Preparing sign-in.": "ログインを準備中です。",
  "Finishing sign-in...": "ログインを完了中…",
  "Signing in...": "ログイン中…",
  "Open sign-in page": "ログイン画面を開く",
  "Open ChatGPT sign-in": "ChatGPTログインを開く",
  "Retry connection": "接続を再試行",
  "Finish signing in in your browser.": "ブラウザーでログインを完了してください。",
  "Codex setup failed. Try again.": "Codexの設定に失敗しました。もう一度お試しください。",
  "Ask anything...": "何でも質問してください…",
  "Ask anything, @tag files/folders, $use skills, or / for commands":
    "質問を入力。@でファイル、$でスキル、/でコマンドを指定できます",
  "Send message": "メッセージを送信",
  "Queue message": "メッセージを順番待ちに追加",
  Sending: "送信中",
  "Sending...": "送信中…",
  "Stop generation": "生成を停止",
  "Environment disconnected": "環境への接続が切れています",
  "Preparing worktree": "作業ツリーを準備中",
  "Previous question": "前の質問",
  "Next question": "次の質問",
  "Submit answers": "回答を送信",
  "Submit answer": "回答を送信",
  Submit: "送信",
  Next: "次へ",
  "Submitting...": "送信中…",
  Refine: "調整",
  Implement: "実装",
  "Implementation actions": "実装の操作",
  "Implement in new thread": "新しいスレッドで実装",
  "Attach files": "ファイルを添付",
  "Expand composer": "入力欄を広げる",
  "Runtime mode": "実行モード",
  "Write custom answer": "回答を入力",
  Plan: "計画",
  Default: "既定",
  Model: "モデル",
  Permissions: "権限",
  "Worktree cleanup": "作業ツリーの整理",
  "Artifacts and logs": "成果物とログ",
  "Project defaults and overrides": "プロジェクトの既定値と個別設定",
  "Project overview": "プロジェクト概要",
  "Default model": "既定のモデル",
  Notifications: "通知",
  Theme: "テーマ",
  Font: "フォント",
  Language: "言語",
  Advanced: "詳細設定",
  Reset: "リセット",
  "Add provider": "プロバイダーを追加",
  "Add account": "アカウントを追加",
  "Provider settings": "プロバイダー設定",
  "No results": "結果がありません",
  "No results found.": "結果が見つかりません。",
  Search: "検索",
  "Enabled providers": "有効なプロバイダー",
  "Binary path": "実行ファイルのパス",
  Build: "実装",
  "Use existing CLI": "既存のCLIを使用",
  "Continue with ChatGPT": "ChatGPTで続ける",
  "Connected to ChatGPT.": "ChatGPTに接続済みです。",
  "Enable a provider in Settings": "設定でプロバイダーを有効にしてください",
  "Enable a provider in Settings to send a message":
    "送信するには、設定でプロバイダーを有効にしてください",
  SnapShots: "画面キャプチャ",
  "Color scheme": "配色",
  Themes: "テーマ",
  Contrast: "コントラスト",
  "Glass opacity": "透明度",
  "Diff colors": "差分の色",
  "Chat width": "チャットの幅",
  "Panel animations": "パネルのアニメーション",
  "Environment identification": "環境の識別",
  "Interface font": "画面のフォント",
  "Prompt font": "入力欄のフォント",
  "Code font": "コードのフォント",
  "Terminal font": "ターミナルのフォント",
  "Font smoothing": "文字の滑らかさ",
  "Word wrap": "行の折り返し",
  "Project grouping": "プロジェクトのグループ化",
  "Auto-settle inactive threads": "使っていないスレッドを自動で完了",
  "Auto-settle merged threads": "マージ済みスレッドを自動で完了",
  "Days of inactivity before auto-settle": "自動完了までの日数",
  "Thread notifications": "スレッドの通知",
  "In-app notifications": "アプリ内の通知",
  "Time format": "時刻の表示",
  "Response streaming": "回答のストリーミング",
  "Hide whitespace changes": "空白だけの差分を非表示",
  "Default diff file state": "差分ファイルの既定の表示",
  "Diff layout": "差分のレイアウト",
  "Proactive panels": "パネルの自動表示",
  "Show skills in slash menu": "スラッシュメニューにスキルを表示",
  "Rich text composer": "入力欄の書式設定",
  "Collapse composer on scroll": "スクロール時に入力欄を折りたたむ",
  "Send shortcut": "送信ショートカット",
  "Follow-up behavior": "追加入力の動作",
  "Provider update checks": "プロバイダーの更新確認",
  "Continue threads after restarts": "再起動後にスレッドを継続",
  "Background activity": "バックグラウンドの動作",
  "New threads": "新しいスレッド",
  Submodules: "サブモジュール",
  "Start from origin": "originから開始",
  "Add project starts in": "プロジェクト追加時の開始場所",
  "Unpin confirmation": "ピン留め解除の確認",
  "Archive confirmation": "アーカイブの確認",
  "Delete confirmation": "削除の確認",
  "Quit shortcut": "終了ショートカット",
  "Text generation model": "文章生成モデル",
  Diagnostics: "診断",
  "Open source licenses": "オープンソースライセンス",
  "Plan mode (legacy)": "計画モード（旧設定）",
  "Context window indicator (legacy)": "コンテキスト表示（旧設定）",
  "Sidebar (legacy)": "サイドバー（旧設定）",
  "Include app text": "アプリ内の文字を含める",
  "Capture shortcut": "キャプチャのショートカット",
  "Capture sound": "キャプチャ音",
  "Capture flash": "キャプチャのフラッシュ",
  "Capture animations": "キャプチャのアニメーション",
  "Usage providers": "使用量の取得元",
  "Cursor account usage": "Cursorアカウントの使用量",
  "Health check interval": "状態確認の間隔",
  "Agent browser access": "エージェントのブラウザーアクセス",
  "Device hosts": "接続先の端末",
  "Agent device access": "エージェントの端末アクセス",
  "Device hub": "端末ハブ",
  "Simulator support": "シミュレーターの対応",
  "Browser profiles": "ブラウザープロファイル",
  "Default browser profile": "既定のブラウザープロファイル",
  "Default browser viewport": "既定のブラウザー表示サイズ",
  "Default browser zoom": "既定のブラウザー倍率",
  "Default browser appearance": "既定のブラウザー外観",
  "Browser recording frame rate": "ブラウザー録画のフレームレート",
  "Show key presses in recordings": "録画にキー入力を表示",
  "Show mouse presses in recordings": "録画にマウス操作を表示",
  "Open links in": "リンクを開く場所",
  "Auto-show floating preview": "プレビューを自動表示",
  "Automatically pull": "自動でpull",
  "Default merge method": "既定のマージ方法",
  "Source control": "ソース管理",
  "Git fetch interval": "Gitのfetch間隔",
  "Bitbucket credentials": "Bitbucketの認証",
  "Source control writing style": "ソース管理の文章スタイル",
  "Follow change request templates": "変更依頼テンプレートを使用",
  "Source control writer model": "ソース管理の文章生成モデル",
  Actions: "アクション",
  "Environment icon": "環境のアイコン",
  "Local environment": "ローカル環境",
  "Network access": "ネットワークアクセス",
  "Tailscale HTTPS": "Tailscale HTTPS",
  "WSL backend": "WSLバックエンド",
  "Publish agent activity": "エージェントの動作を共有",
  "This machine": "このMac",
  Environments: "環境",
  "Load balancing": "負荷分散",
  "GitHub sharing": "GitHubの共有",
  "Archived threads": "アーカイブ済みスレッド",
  "Search settings…": "設定を検索…",
  "No settings found.": "設定が見つかりません。",
  Active: "作業中",
  Settled: "完了",
  "Search threads...": "スレッドを検索…",
  "Select project": "プロジェクトを選択",
  "New project": "新しいプロジェクト",
  "Search threads": "スレッドを検索",
  "Clear thread search": "スレッドの検索を解除",
  "New thread in current project: Shift+click":
    "現在のプロジェクトに新しいスレッド：Shift+クリック",
  "Do not import projects": "プロジェクトを取り込まない",
  "Select none": "選択を解除",
  "Looking for projects from Claude Code and Codex…":
    "Claude CodeとCodexのプロジェクトを検索しています…",
  "No projects yet": "まだプロジェクトがありません",
  "No threads yet": "まだスレッドがありません",
  "Local folder": "ローカルフォルダー",
  "Browse a folder on disk": "このMacのフォルダーを選択",
  "Git URL": "GitのURL",
  Navigate: "移動",
  Select: "選択",
  Add: "追加",
  Directories: "フォルダー",
  "Thread breadcrumb": "スレッドの場所",
};
